#include "main.h"
#include "stdio.h"
#include "stdlib.h"
#include "stdbool.h"
#include "stdarg.h"
#include "string.h"
#include "arm_math.h"
#include "arm_const_structs.h"
#include "math.h"

#include "gpio_app.h"
#include "uart_app.h"
#include "isr_app.h"
#include "iic_app.h"
#include "fft_app.h"
#include "pid.h"
#include "pid_app.h"
#include "pwm_app.h"
#include "scheduler.h"
#include "data_proc.h"

#include "24c02.h"
#include "motor.h"